# Generated by Django 3.1.4 on 2021-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20210111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='course_outline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
