# Generated by Django 3.1.4 on 2021-01-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPA_Conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_conversions_id', models.IntegerField()),
                ('course_outline_id', models.IntegerField()),
                ('lowerGrade', models.TextField()),
                ('upperGrade', models.TextField()),
                ('T_sign', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
