# Generated by Django 3.1.4 on 2021-01-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_conversions', '0002_auto_20210111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa_conversions',
            name='T_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpa_conversions',
            name='course_outline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpa_conversions',
            name='lowerGrade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpa_conversions',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpa_conversions',
            name='upperGrade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
