# Generated by Django 3.1.4 on 2021-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended_textbooks', '0002_auto_20210111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended_textbooks',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommended_textbooks',
            name='course_outline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommended_textbooks',
            name='edition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommended_textbooks',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommended_textbooks',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
