# Generated by Django 3.1.4 on 2021-01-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate_Attributes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_outline_id', models.IntegerField(blank=True, null=True)),
                ('publicID', models.IntegerField(blank=True, null=True)),
                ('grad', models.TextField(blank=True, null=True)),
                ('instruct', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
