# Generated by Django 3.1.4 on 2021-01-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_update',
            name='course_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master_update',
            name='course_outline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master_update',
            name='num',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_update',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
