# Generated by Django 3.1.4 on 2021-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20210111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='course_outline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='fname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='lname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='office',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
