# Generated by Django 3.1.4 on 2021-01-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching_Assistants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_outline_id', models.IntegerField(blank=True, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('fname', models.TextField(blank=True, null=True)),
                ('lname', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('office', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
