# Generated by Django 3.1.4 on 2021-01-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_objectives_id', models.IntegerField()),
                ('course_outline_id', models.IntegerField()),
                ('publicID', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
    ]
