# Generated by Django 3.1.4 on 2021-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0002_auto_20210111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_information',
            name='calendar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar_information',
            name='course_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar_information',
            name='course_outline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar_information',
            name='credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar_information',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar_information',
            name='hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
