# Generated by Django 3.1.4 on 2021-01-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0003_auto_20210113_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar_information',
            old_name='calendar',
            new_name='link',
        ),
        migrations.AddField(
            model_name='calendar_information',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
