# Generated by Django 3.1.4 on 2021-01-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_information', '0004_auto_20210114_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_information',
            name='num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
