# Generated by Django 3.1.4 on 2020-12-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_echo_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echo',
            name='number',
        ),
        migrations.RemoveField(
            model_name='echo',
            name='theString',
        ),
    ]
