# Generated by Django 3.1.4 on 2021-01-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_grades', '0003_auto_20210113_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_grades',
            name='learningOutcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
